server:
  port: ${PORT:8081}

spring:
  application:
    name: product-api

  datasource:
    url: jdbc:postgresql://localhost:5433/product-db
    username: admin
    password: 123456

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  sql:
    init:
      platform: postgresql